// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  about_slice: dynamic(() => import("./AboutSlice")),
  blog_list: dynamic(() => import("./BlogList")),
  contact: dynamic(() => import("./Contact")),
  contact_form: dynamic(() => import("./ContactForm")),
  hero: dynamic(() => import("./Hero")),
  policy_slice: dynamic(() => import("./PolicySlice")),
  service: dynamic(() => import("./Service")),
  service_home: dynamic(() => import("./ServiceHome")),
  service_list: dynamic(() => import("./ServiceList")),
  service_section: dynamic(() => import("./ServiceSection")),
};
